version: "3"
services:
# The dev container is not actually used, it is just handy to run `docker-compose up dev` to start all services
  dev: 
    image: btcpayserver/dash:0.14.0
    environment:
      BITCOIN_NETWORK: regtest
      BITCOIN_EXTRA_ARGS: |
        deprecatedrpc=signrawtransaction
        connect=dashd:9998
    links:
      - nbxplorer
      - postgres

     
  nginx:
    restart: unless-stopped
    image: nginx:latest
    container_name: nginx
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - "nginx_conf:/etc/nginx/conf.d"
    - "nginx_vhost:/etc/nginx/vhost.d"
    - "nginx_html:/usr/share/nginx/html"
    - "nginx_certs:/etc/nginx/certs:ro"
  nginx-gen:
    restart: unless-stopped
    image: btcpayserver/docker-gen:0.7.5
    container_name: nginx-gen
    volumes:
    - "/var/run/docker.sock:/tmp/docker.sock:ro"
    - "./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro"
    - "nginx_conf:/etc/nginx/conf.d"
    - "nginx_vhost:/etc/nginx/vhost.d"
    - "nginx_html:/usr/share/nginx/html"
    - "nginx_certs:/etc/nginx/certs:ro"
    entrypoint: /usr/local/bin/docker-gen -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    links:
    - btcpayserver
    - nginx
  letsencrypt-nginx-proxy-companion:
    restart: unless-stopped
    image: btcpayserver/letsencrypt-nginx-proxy-companion:1.10.0
    container_name: letsencrypt-nginx-proxy-companion
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock:ro"
    - "nginx_conf:/etc/nginx/conf.d"
    - "nginx_vhost:/etc/nginx/vhost.d"
    - "nginx_html:/usr/share/nginx/html"
    - "nginx_certs:/etc/nginx/certs:rw"
    environment:
      NGINX_DOCKER_GEN_CONTAINER: "nginx-gen"
      NGINX_PROXY_CONTAINER: "nginx"
      ACME_CA_URI: ${ACME_CA_URI:-https://acme-staging.api.letsencrypt.org/directory}
    links:
    - nginx-gen
  btcpayserver:
    restart: unless-stopped
    image: ${BTCPAY_IMAGE:-btcpayserver/btcpayserver:1.0.3.105}
    expose:
    - "49392"
    environment:
      BTCPAY_POSTGRES: User ID=postgres;Host=postgres;Port=5432;Database=btcpayserver${NBITCOIN_NETWORK:-regtest}
      BTCPAY_NETWORK: ${NBITCOIN_NETWORK:-regtest}
      BTCPAY_BIND: 0.0.0.0:49392
      BTCPAY_ROOTPATH: ${BTCPAY_ROOTPATH:-/}
      BTCPAY_SSHCONNECTION: "root@host.docker.internal"
      BTCPAY_SSHTRUSTEDFINGERPRINTS: ${BTCPAY_SSHTRUSTEDFINGERPRINTS}
      BTCPAY_SSHKEYFILE: ${BTCPAY_SSHKEYFILE}
      BTCPAY_DEBUGLOG: btcpay.log
      VIRTUAL_NETWORK: nginx-proxy
      VIRTUAL_PORT: 49392
      VIRTUAL_HOST: ${BTCPAY_HOST}
      VIRTUAL_HOST_NAME: "btcpay"
      SSL_POLICY: Mozilla-Modern
      LETSENCRYPT_HOST: ${BTCPAY_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL:-<no value>}
      BTCPAY_CHAINS: "dash"
      BTCPAY_DASHEXPLORERURL: http://nbxplorer:32838/
    links:
    - postgres
    volumes:
    - "btcpay_datadir:/datadir"
    - "nbxplorer_datadir:/root/.nbxplorer"
  nbxplorer:
    restart: unless-stopped
    image: nicolasdorier/nbxplorer:2.0.0.45
    expose:
    - "32838"
    environment:
      NBXPLORER_NETWORK: ${NBITCOIN_NETWORK:-regtest}
      NBXPLORER_BIND: 0.0.0.0:32838
      NBXPLORER_SIGNALFILESDIR: /datadir
      NBXPLORER_CHAINS: "dash"
      NBXPLORER_DASHRPCURL: http://dashd:9998/
      NBXPLORER_DASHNODEENDPOINT: dashd:9999
    volumes:
    - "nbxplorer_datadir:/datadir"
    - "dash_datadir:/root/.dashcore"
  postgres:
    restart: unless-stopped
    image: postgres:9.6.5
    volumes:
    - "postgres_datadir:/var/lib/postgresql/data"
  dashd:
    restart: unless-stopped
    container_name: btcpayserver_dashd
    image: btcpayserver/dash:0.14.0
    environment:
      BITCOIN_EXTRA_ARGS: |
        ${NBITCOIN_NETWORK:-regtest}=1
        port=9999
        rpcport=9998
        whitelist=0.0.0.0/0
    expose:
    - "9998"
    - "9999"
    volumes:
    - "dash_datadir:/data"
volumes:
  nginx_conf: 
  nginx_vhost: 
  nginx_html: 
  nginx_certs: 
  btcpay_datadir: 
  nbxplorer_datadir: 
  postgres_datadir: 
  dash_datadir: 
networks: {}
